name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest

      - uses: actions/checkout@v2

      - uses: actions/setup-go@v1
          with:
            go-version: '1.15'

      - name: Tests
        run: |
          go test ./...
